package com.Wsdl2Code.WebServices.PredictionsService;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 10/19/2017 10:20:46 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import com.Wsdl2Code.WebServices.PredictionsService.RealBoundary;

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;

import java.util.Hashtable;

import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class BoundarySpatial implements KvmSerializable {

    public RealBoundary latitude;
    public RealBoundary longitude;

    public BoundarySpatial() {
    }

    public BoundarySpatial(SoapObject soapObject) {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("latitude")) {
            SoapObject j = (SoapObject) soapObject.getProperty("latitude");
            latitude = new RealBoundary(j);

        }
        if (soapObject.hasProperty("longitude")) {
            SoapObject j = (SoapObject) soapObject.getProperty("longitude");
            longitude = new RealBoundary(j);

        }
    }

    @Override
    public Object getProperty(int arg0) {
        switch (arg0) {
            case 0:
                return latitude;
            case 1:
                return longitude;
        }
        return null;
    }

    @Override
    public int getPropertyCount() {
        return 2;
    }

    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch (index) {
            case 0:
                info.type = RealBoundary.class;
                info.name = "latitude";
                break;
            case 1:
                info.type = RealBoundary.class;
                info.name = "longitude";
                break;
        }
    }

    //    @Override
    public String getInnerText() {
        return null;
    }


    //    @Override
    public void setInnerText(String s) {
    }


    @Override
    public void setProperty(int arg0, Object arg1) {
    }

}
