package com.Wsdl2Code.WebServices.PredictionsService;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 10/19/2017 10:20:46 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import com.Wsdl2Code.WebServices.PredictionsService.BoundaryDate;
import com.Wsdl2Code.WebServices.PredictionsService.BoundaryDepth;
import com.Wsdl2Code.WebServices.PredictionsService.VectorMetadata;
import com.Wsdl2Code.WebServices.PredictionsService.VectorSpatialCoordinate;

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;

import java.util.Hashtable;
import java.util.Vector;

import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class Data implements KvmSerializable {

    public BoundaryDate boundaryDate;
    public BoundaryDepth boundaryDepth;
    public VectorMetadata metadata;
    public VectorSpatialCoordinate spatialCoordinates;
    public String value;

    public Data() {
    }

    public Data(SoapObject soapObject) {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("boundaryDate")) {
            SoapObject j = (SoapObject) soapObject.getProperty("boundaryDate");
            boundaryDate = new BoundaryDate(j);

        }
        if (soapObject.hasProperty("boundaryDepth")) {
            SoapObject j = (SoapObject) soapObject.getProperty("boundaryDepth");
            boundaryDepth = new BoundaryDepth(j);

        }
        if (soapObject.hasProperty("metadata")) {
            Vector<SoapObject> j = (Vector<SoapObject>) soapObject.getProperty("metadata");
            metadata = new VectorMetadata(j);
        }
        if (soapObject.hasProperty("spatialCoordinates")) {

            Vector<SoapObject> j = (Vector<SoapObject>) soapObject.getProperty("spatialCoordinates");
            spatialCoordinates = new VectorSpatialCoordinate(j);
        }
        if (soapObject.hasProperty("value")) {
            Object obj = soapObject.getProperty("value");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                value = j.toString();
            } else if (obj != null && obj instanceof String) {
                value = (String) obj;
            }
        }
    }

    @Override
    public Object getProperty(int arg0) {
        switch (arg0) {
            case 0:
                return boundaryDate;
            case 1:
                return boundaryDepth;
            case 2:
                return metadata;
            case 3:
                return spatialCoordinates;
            case 4:
                return value;
        }
        return null;
    }

    @Override
    public int getPropertyCount() {
        return 5;
    }

    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch (index) {
            case 0:
                info.type = BoundaryDate.class;
                info.name = "boundaryDate";
                break;
            case 1:
                info.type = BoundaryDepth.class;
                info.name = "boundaryDepth";
                break;
            case 2:
                info.type = PropertyInfo.VECTOR_CLASS;
                info.name = "metadata";
                break;
            case 3:
                info.type = PropertyInfo.VECTOR_CLASS;
                info.name = "spatialCoordinates";
                break;
            case 4:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "value";
                break;
        }
    }

    //    @Override
    public String getInnerText() {
        return null;
    }


    //    @Override
    public void setInnerText(String s) {
    }


    @Override
    public void setProperty(int arg0, Object arg1) {
    }

}
