package com.Wsdl2Code.WebServices.PredictionsService;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 10/19/2017 10:20:46 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;

import java.util.Hashtable;

import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class StringBoundary implements KvmSerializable {

    public String max;
    public String min;

    public StringBoundary() {
    }

    public StringBoundary(SoapObject soapObject) {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("max")) {
            Object obj = soapObject.getProperty("max");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                max = j.toString();
            } else if (obj != null && obj instanceof String) {
                max = (String) obj;
            }
        }
        if (soapObject.hasProperty("min")) {
            Object obj = soapObject.getProperty("min");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                min = j.toString();
            } else if (obj != null && obj instanceof String) {
                min = (String) obj;
            }
        }
    }

    @Override
    public Object getProperty(int arg0) {
        switch (arg0) {
            case 0:
                return max;
            case 1:
                return min;
        }
        return null;
    }

    @Override
    public int getPropertyCount() {
        return 2;
    }

    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch (index) {
            case 0:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "max";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "min";
                break;
        }
    }

    //    @Override
    public String getInnerText() {
        return null;
    }


    //    @Override
    public void setInnerText(String s) {
    }


    @Override
    public void setProperty(int arg0, Object arg1) {
    }

}
